from tkinter import *
from time import sleep
def add():
    a=int(E1.get())
    b=int(E2.get())
    ad=(a+b)
    E3.delete(0,END)
    E3.insert(10,ad)
def sub():
    a=int(E1.get())
    b=int(E2.get())
    diff=(a-b)
    E3.delete(0,END)
    E3.insert(10,diff)
def mul():

    a=int(E1.get())
    b=int(E2.get())
    m=(a*b)
    E3.delete(0,END)
    E3.insert(10,m)
def div():
    a=int(E1.get())
    b=int(E2.get())
    d=(a/b)
    E3.delete(0,END)
    E3.insert(10,d)
root=Tk()
root.title("arithmetic")
root.geometry("500x500")
topFrame=Frame(root)
topFrame.pack()
l1=Label(root,text="a")
l1.pack(side=LEFT)
E1=Entry(root,width=20)
E1.pack(side=LEFT,padx=10,pady=10)
l2=Label(root,text="b")
l2.pack(side=RIGHT)
E2=Entry(root,width=20)
E2.pack(side=RIGHT,padx=10,pady=10)
l3=Label(root,text="result")
l3.pack(side=TOP)
E3=Entry(root,width=20)
E3.pack(side=TOP)
b1=Button(topFrame,text="add",command=add)
b1.grid()
b2=Button(topFrame,text="sub",command=sub)
b2.grid()
b3=Button(topFrame,text="multiply",command=mul)
b3.grid()
b4=Button(topFrame,text="divide",command=div)
b4.grid()

root.mainloop()
